"""add foreign key to Review

Revision ID: 332483e23d4c
Revises: cc93792ebd5c
Create Date: 2024-06-26 16:45:43.301273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332483e23d4c'
down_revision = 'cc93792ebd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
